name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'    # Troque para a sua versão de Java, se for diferente
          distribution: 'temurin'

      - name: Rodar testes Maven
        run: ./mvnw clean test